Base:
    model_id: ganf
    normalize: 'minmax'

ganf_SMD:
    dataset_id: SMD
    window_size: 100
    stride: 1
    n_blocks: 1
    input_size: 1
    hidden_size: 32
    n_hidden: 1
    dropout: 0.1
    batch_norm: False
    batch_size: 512
    weight_decay: 5.0e-4
    nb_epoch: 10
    lr: 2.0e-3
    h_tol: 1.0e-4
    rho_max: 1000000
    lambda1: 0.0
    rho_init: 1.0
    alpha_init: 0.0
    shuffle: True
    num_workers: 1
    device: 0
ganf_ASD:
    dataset_id: ASD
    window_size: 100
    stride: 1
    n_blocks: 1
    input_size: 1
    hidden_size: 32
    n_hidden: 1
    dropout: 0.1
    batch_norm: False
    batch_size: 512
    weight_decay: 5.0e-4
    nb_epoch: 10
    lr: 2.0e-3
    h_tol: 1.0e-4
    rho_max: 1000000
    lambda1: 0.0
    rho_init: 1.0
    alpha_init: 0.0
    shuffle: True
    num_workers: 1
    device: 0
ganf_SWAT:
    dataset_id: SWAT
    window_size: 100
    stride: 1
    n_blocks: 1
    input_size: 1
    hidden_size: 32
    n_hidden: 1
    dropout: 0.1
    batch_norm: False
    batch_size: 512
    weight_decay: 5.0e-4
    nb_epoch: 10
    lr: 2.0e-3
    h_tol: 1.0e-4
    rho_max: 1000000
    lambda1: 0.0
    rho_init: 1.0
    alpha_init: 0.0
    shuffle: True
    num_workers: 1
    device: 0
ganf_WADI:
    dataset_id: WADI
    window_size: 100
    stride: 1
    n_blocks: 1
    input_size: 1
    hidden_size: 32
    n_hidden: 1
    dropout: 0.1
    batch_norm: False
    batch_size: 512
    weight_decay: 5.0e-4
    nb_epoch: 10
    lr: 2.0e-3
    h_tol: 1.0e-4
    rho_max: 1000000
    lambda1: 0.0
    rho_init: 1.0
    alpha_init: 0.0
    shuffle: True
    num_workers: 1
    device: 0
ganf_SMAP:
    dataset_id: SMAP
    window_size: 100
    stride: 1
    n_blocks: 1
    input_size: 1
    hidden_size: 32
    n_hidden: 1
    dropout: 0.1
    batch_norm: False
    batch_size: 512
    weight_decay: 5.0e-4
    nb_epoch: 10
    lr: 2.0e-3
    h_tol: 1.0e-4
    rho_max: 1000000
    lambda1: 0.0
    rho_init: 1.0
    alpha_init: 0.0
    shuffle: True
    num_workers: 1
    device: 0
ganf_MSL:
    dataset_id: MSL
    window_size: 100
    stride: 1
    n_blocks: 1
    input_size: 1
    hidden_size: 32
    n_hidden: 1
    dropout: 0.1
    batch_norm: False
    batch_size: 512
    weight_decay: 5.0e-4
    nb_epoch: 10
    lr: 2.0e-3
    h_tol: 1.0e-4
    rho_max: 1000000
    lambda1: 0.0
    rho_init: 1.0
    alpha_init: 0.0
    shuffle: True
    num_workers: 1
    device: 0